config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'home' => 'home#index'
  post 'home' => 'home#post'

  get 'search' => 'search#index'

  resources :tweets do
    resources :comments, only:[:create]
  end

  resources :users, only:[:show] do
    member do
      get :following, :followers
    end
  end

  resources :friendships, only:[:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :following, class_name:  'User',
                         foreign_key: 'followee_id'
  validates :followee_id, presence: true

  belongs_to :follower, class_name:  'User',
                        foreign_key: 'follower_id'
  validates :follower_id, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  has_many :tweets

  has_many :comments

  has_many :following_friendships, class_name:  'Friendship',
                                   foreign_key: 'follower_id',
                                   dependent: :destroy
  has_many :followings, through: :following_friendships

  has_many :follower_friendships, class_name:  'Friendship',
                                  foreign_key: 'followee_id',
                                  dependent: :destroy
  has_many :followers, through: :follower_friendships

  def following?(other_user)
    following_friendships.find_by(followee_id: other_user.id)
  end

  def follow!(other_user)
    following_friendships.create!(followee_id: other_user.id)
  end

  def unfollow!(other_user)
    following_friendships.find_by(followee_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to tweet_path(@comment.tweet)
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @user = User.find(params[:friendship][:followee_id])
    current_user.follow!(@user)
    redirect_to user_path(@user)
  end

  def destroy
    @user = Friendship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to user_path(@user)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @tweets = Tweet.includes(:user).order('updated_at DESC').page(params[:page]).per(5)
    @tweet = Tweet.new
  end

  def post
    current_user.tweets.create(tweet_params)
    redirect_to root_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:image, :text)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @tweets = Tweet.where('text LIKE(?)', "%#{ search_params[:keyword] }%").order('text DESC').page(params[:page]).per(5)
  end

  private

  def search_params
    params.permit(:keyword)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if current_user.id == tweet.user_id
    redirect_to root_path
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params) if current_user.id == tweet.user_id
    redirect_to root_path
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  private

  def tweet_params
    params.permit(:image, :text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).per(5).order('created_at DESC')
    @followings = @user.followings
    @followers = @user.followers
  end

  def following
    @user = User.find(params[:id])
    @followings = @user.followings
    @followers = @user.followers
  end

  def followers
    @user = User.find(params[:id])
    @followings = @user.followings
    @followers = @user.followers
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.contents.row
  .container.tweet_post_container
    = form_for @tweet, url: { action: 'post' }, html: { class: 'tweet_post' } do |f|
      = f.text_field :image, placeholder: 'Image Url', class: 'tweet_post__image'
      = f.text_field :text, cols: '30', placeholder: 'text', rows: '1', class: 'tweet_post__text'
      = f.submit 'POST', class: 'tweet_post__post_button'

  - @tweets.each do |tweet|
    = render partial: "tweets/tweet", locals: { tweet: tweet }
  = paginate(@tweets)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pics
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    :javascript
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
  %body
    %header.header
      .header__bar.row
        %h1.grid-4
          = link_to 'Pics', root_path
        - if user_signed_in?
          .user_nav.grid-8
            .grid-6
              = form_tag(search_path, method: :get) do
                %input.search_box{ placeholder: 'search', type: 'text', name: 'keyword' }
            .grid-6
              %span
                = current_user.nickname
                %ul.user__info
                  %li
                    = link_to 'my page', user_path(current_user), method: :get
                    = link_to 'sign out', destroy_user_session_path, method: :delete
        - else
          .grid-6
            = link_to 'sign in', new_user_session_path, class: 'post'
            = link_to "sign up", new_user_registration_path, class: 'post'
    = yield
    %footer
      %p
        Copyright PicTweet 2014.

app/views/search/index.html.haml
.contents.row
  - @tweets.each do |tweet|
    = render partial: "tweets/tweet", locals: { tweet: tweet }
  = paginate(@tweets)

app/views/tweets/_tweet.html.haml
.content_post{style: "background-image: url(#{tweet.image});"}
  .more
    %span
      = image_tag 'arrow_top.png'
    %ul.more_list
      %li
        = link_to '詳細', tweet_path(tweet)
      - if current_user.id == tweet.user.id
        %li
          = link_to '編集', edit_tweet_path(tweet)
        %li
          = link_to '削除', tweet_path(tweet), method: :delete
  = simple_format(tweet.text)
  %span.name
    = link_to user_path(tweet.user) do
      %span 投稿者
      = tweet.user.nickname

app/views/tweets/edit.html.haml
.contents.row
  = form_tag(tweet_path(@tweet), method: :patch) do
    %h3 投稿する
    %input{placeholder: 'Image Url', type: 'text', name: 'image', value: "#{@tweet.image}", autofocus: 'true'}
    %textarea{cols: '30', name: 'text', placeholder: 'text', rows: '10'}
      = @tweet.text
    %input{type: 'submit', value: 'SENT'}

app/views/tweets/show.html.haml
.contents.row
  .content_post{style: "background-image: url(#{@tweet.image});"}
    .more
      %span
        = image_tag 'arrow_top.png'
      %ul.more_list
        %li
          = link_to '詳細', tweet_path(@tweet)
        - if user_signed_in? && current_user.id == @tweet.user.id
          %li
            = link_to '編集', edit_tweet_path(@tweet)
          %li
            = link_to '削除', tweet_path(@tweet), method: :delete
    = simple_format(@tweet.text)
    %span.name
      = link_to user_path(current_user) do
        %span 投稿者
        = @tweet.user.nickname
  .container
    - if current_user
      = form_tag("/tweets/#{@tweet.id}/comments", method: :post) do
        %textarea{ cols: "30", name:"text", placeholder: "コメントする", rows:"2" }
        %input{ type: "submit", value: "SENT" }
    .comments
      %h4 コメント一覧
      - if @comments
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.nickname, user_path(@tweet.user)
              ：
              = comment.text

app/views/users/followers.html.haml
.contents.row.following_or_followers
  .container.user_show_profile
    %p
      = link_to @user.nickname, user_path(@user), class: 'user_show_profile__name'
  %p
    %span
      = @followers.size
    followers&emsp;&emsp;
  %ul
    - @followers.each do |follower|
      %li.container.user_bar
        = link_to follower.nickname, user_path(follower)

app/views/users/following.html.haml
.contents.row.following_or_followers
  .container.user_show_profile
    %p
      = link_to @user.nickname, user_path(@user), class: 'user_show_profile__name'
  %p
    %span
      = @followings.size
    follow&emsp;&emsp;
  %ul
    - @followings.each do |following|
      %li.container.user_bar
        = link_to following.nickname, user_path(following)

app/views/users/show.html.haml
.contents.row
  .container.user_show_profile
    %p.user_show_profile__name
      = @user.nickname
    %p
      %span
        = @tweets.size
      tweets&emsp;&emsp;
      = link_to following_user_path(@user) do
        %span
          = @followings.size
        follow&emsp;&emsp;
      = link_to followers_user_path(@user) do
        %span
          = @followers.size
        followers

    - if current_user != @user
      - if current_user.following?(@user)
        = form_for(current_user.following_friendships.find_by(followee_id: @user.id), html: { method: :delete }) do |f|
          = f.submit 'unfollow'
      - else
        = form_for(current_user.following_friendships.build(followee_id: @user.id)) do |f|
          = f.hidden_field :followee_id
          = f.submit 'follow'

  - @tweets.each do |tweet|
    = render partial: "tweets/tweet", locals: { tweet: tweet }

  = paginate(@tweets)